
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 26 02:16:30 CST 2019
//----------------------------------------------------

package backend.analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos_Kok {
  /* terminals */
  public static final int CerrarParentesis = 33;
  public static final int PositionY = 14;
  public static final int PositionX = 13;
  public static final int Numero = 31;
  public static final int Comentario = 30;
  public static final int Right = 5;
  public static final int Mas = 24;
  public static final int ToCenter = 10;
  public static final int PositionXY = 12;
  public static final int Clears = 7;
  public static final int PenDown = 9;
  public static final int Repeat = 19;
  public static final int ToDraw = 18;
  public static final int ShowTurtle = 16;
  public static final int Hexa = 29;
  public static final int Coma = 22;
  public static final int ErrorLexico = 2;
  public static final int Left = 6;
  public static final int Asterisco = 27;
  public static final int AbrirCorchetes = 20;
  public static final int EOF = 0;
  public static final int Diagonal = 26;
  public static final int error = 1;
  public static final int Variable = 28;
  public static final int Menos = 25;
  public static final int PenUp = 8;
  public static final int Igual = 23;
  public static final int Backward = 4;
  public static final int ToErase = 17;
  public static final int AbrirParentesis = 32;
  public static final int CerrarCorchetes = 21;
  public static final int Color = 11;
  public static final int Forward = 3;
  public static final int HideTurtle = 15;
}

