package gui.ventanas;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jonyasus
 */
public class Tortuga extends javax.swing.JPanel {

    /**
     * Creates new form ImageLoager
     */
    
    BufferedImage img;
    double rotateAngle;
    
    public Tortuga() {
        initComponents();
        img = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void loadimage(String FilePath) throws IOException{
     img=ImageIO.read(new File(FilePath));
    }
    
    public void RotateImage(int angle){
        rotateAngle = angle;
        repaint();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        if(img!=null){
            Graphics2D g2D = (Graphics2D)g;
            g2D.translate(this.getSize().width/2, this.getSize().height/2);
            g2D.rotate(Math.toRadians(rotateAngle));
            g2D.drawImage(img, -img.getWidth()/2, -img.getHeight()/2, null);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
